// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJICJMw_PwQNVpolSCDlO451u_bFMVacE',
    appId: '1:58386275112:web:af040cef42f1ed7a7e8e1d',
    messagingSenderId: '58386275112',
    projectId: 'strongercorev2',
    authDomain: 'strongercorev2.firebaseapp.com',
    databaseURL: 'https://strongercorev2-default-rtdb.firebaseio.com',
    storageBucket: 'strongercorev2.appspot.com',
    measurementId: 'G-WZWDTKW7X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4K-iNO-4fRtBG0H2Vaza7BF2XFDnqyA4',
    appId: '1:58386275112:android:4b334577ca7247f07e8e1d',
    messagingSenderId: '58386275112',
    projectId: 'strongercorev2',
    databaseURL: 'https://strongercorev2-default-rtdb.firebaseio.com',
    storageBucket: 'strongercorev2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUu18VrD-EqV8fIIKIjGPf_QaNcnknThQ',
    appId: '1:58386275112:ios:1263deaedf9f06c77e8e1d',
    messagingSenderId: '58386275112',
    projectId: 'strongercorev2',
    databaseURL: 'https://strongercorev2-default-rtdb.firebaseio.com',
    storageBucket: 'strongercorev2.appspot.com',
    iosClientId: '58386275112-rgcono0rbtdhm4eutrr6pfhao97mdrlk.apps.googleusercontent.com',
    iosBundleId: 'com.example.strongCore',
  );
}
